M48
; DRILL file {KiCad 9.0.2} date 2025-07-27T12:29:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-27T12:29:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X135.11Y-132.3
X140.89Y-132.3
T2
X117.0Y-91.0
X117.0Y-133.0
X159.0Y-91.0
X159.0Y-133.0
M30
